[package]
name = "runmat-gc-api"
version = "0.2.1"
edition = "2021"
description = "Public API types for the RunMat garbage collector"
homepage = "https://runmat.org"
repository = "https://github.com/runmat-org/runmat"

[dependencies]

