[package]
name = "runmat-turbine"
version = "0.2.7"
edition = "2021"
description = "Cranelift-based JIT compiler for RunMat - the optimizing tier of our V8-inspired execution model"
authors = ["Dystr Team"]
license-file = "../LICENSE.md"
homepage = "https://runmat.org"
repository = "https://github.com/runmat-org/runmat"

[dependencies]
cranelift = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
cranelift-codegen = { workspace = true }
cranelift-native = { workspace = true }
target-lexicon = { workspace = true }
log = { workspace = true }
tracing = "0.1"
thiserror = { workspace = true }
libm = "0.2"
runmat-ignition = { workspace = true }
runmat-builtins = { workspace = true }
runmat-runtime = { workspace = true }
runmat-gc = { workspace = true }
runmat-hir = { workspace = true }
runmat-accelerate = { workspace = true, optional = true }
runmat-time = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
runmat-parser = { workspace = true }

[features]
default = ["native-accel"]
native-accel = ["runmat-ignition/native-accel", "runmat-accelerate"]
