[package]
name = "runmat-lsp"
version = "0.2.6"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
runmat-parser = { workspace = true }
runmat-hir = { workspace = true }
runmat-builtins = { workspace = true }
runmat-lexer = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower-lsp = { workspace = true }
once_cell = { workspace = true }
